'use client';
import {useState,createElement,type HTMLAttributes} from 'react';
import {ArrowUpRight,ArrowRight,BookOpen,Users,Sparkles,CalendarDays,CreditCard,House,Bell,Menu,X,Check,GraduationCap,Settings2,Search,ShieldCheck,ChevronRight,Sun} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {SidebarProvider,Sidebar,SidebarContent,SidebarGroup,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
const roles=['მშობელი','მოსწავლე','მასწავლებელი','ადმინისტრაცია'];
const navs=[{id:'home',label:'მთავარი',icon:House},{id:'schedule',label:'განრიგი',icon:CalendarDays},{id:'library',label:'ბიბლიოთეკა',icon:BookOpen},{id:'payments',label:'გადახდები',icon:CreditCard}];
const lessons=[{name:'ქართული ენა',time:'09:00',room:'ოთახი 204',teacher:'მარიამ კ.'},{name:'მათემატიკა',time:'10:00',room:'ოთახი 208',teacher:'გიორგი მ.'},{name:'ინგლისური ენა',time:'11:00',room:'ოთახი 203',teacher:'ნინო ა.'},{name:'ბუნებისმეტყველება',time:'12:00',room:'ლაბორატორია',teacher:'ანა ჯ.'}];
function Logo(){return <span className="brand-lockup"><img src="/logo-concept.png" width="66" height="66" alt=""/><span className="brand"><strong>აისი</strong><small>სკოლა • AISI SCHOOL</small></span></span>}
function Picker({value,values,onChange,label}:{value:string;values:string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="picker" aria-label={label}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export default function AisiConcept(){
 const [portal,setPortal]=useState(false),[role,setRole]=useState(roles[0]),[tab,setTab]=useState('home'),[menu,setMenu]=useState(false),[dialog,setDialog]=useState(''),[sent,setSent]=useState(false),[child,setChild]=useState('ნიკა'),[day,setDay]=useState(3),[query,setQuery]=useState(''),[theme,setTheme]=useState(false);
 const open=(s:string)=>{setSent(false);setDialog(s)};
 const navigate=(s:string)=>{setTab(s);window.scrollTo({top:0,behavior:'instant'})};
 const switchMode=()=>{setPortal(!portal);setMenu(false);setTab('home');window.scrollTo({top:0,behavior:'instant'})};
 const financial=role===roles[0]||role===roles[3];
 const currentNavs=navs.filter(n=>n.id!=='payments'||financial);
 const changeRole=(r:string)=>{setRole(r);setTab('home')};
 const student=role===roles[0]?child:'ნიკა';
 const dayLessons=student==='ელენე'?[lessons[0],lessons[1],{...lessons[2],name:'ხელოვნება'}, {...lessons[3],name:'მუსიკა'}, {name:'სპორტი',time:'13:00',room:'სპორტული დარბაზი',teacher:'ლევან დ.'}]:lessons;
 return <div className={theme?'alternate-theme':''}><a className="skip" href="#main">მთავარ შინაარსზე გადასვლა</a><div className="concept-bar"><span>ახალი აისი · დიზაინის კონცეფცია</span><button onClick={switchMode}>{portal?'სკოლის ვებგვერდი':'პორტალის დათვალიერება'} <ArrowUpRight size={14}/></button></div>
 {!portal?<><header className="wrap public-header"><button className="logo-button" aria-label="აისი — მთავარი" onClick={()=>window.scrollTo({top:0})}><Logo/></button><nav className={menu?'expanded':''}><a href="#about" onClick={()=>setMenu(false)}>სკოლის შესახებ</a><a href="#learning" onClick={()=>setMenu(false)}>სწავლა</a><a href="#life" onClick={()=>setMenu(false)}>სასკოლო ცხოვრება</a><a href="#contact" onClick={()=>setMenu(false)}>კონტაქტი</a></nav><button className="outline portal-link" onClick={switchMode}>ჩემი აისი <ArrowUpRight size={17}/></button><button className="mobile-menu icon-button" aria-label="მენიუ" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><main id="main">
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow">შენი მომავალი აქ იწყება</div><Heading level={1}>დიდი აღმოჩენები<br/>იწყება <em>აისით.</em></Heading><p>სივრცე, სადაც ცნობისმოყვარეობა ცოდნად იქცევა, ბავშვები კი საკუთარი გზის პოვნას სწავლობენ.</p><div className="hero-actions"><button className="primary" onClick={()=>open('ვიზიტის დაგეგმვა')}>მოდი, გაიცანი აისი <ArrowUpRight size={19}/></button><a className="text-link" href="#about">ჩვენი ხედვა <ArrowRight size={18}/></a></div><div className="hero-note"><Sparkles/><span>ცოდნა. მეგობრობა. ახალი შესაძლებლობები.<small>ერთად, ყოველი ახალი დღიდან.</small></span></div></div><div className="hero-visual"><div className="photo-frame"><img src="/school-life.jpg" alt="სკოლა აისის შენობის ვიზუალიზაცია არსებული ვებგვერდიდან"/><span className="image-label">შენობის ვიზუალიზაცია · არსებული საიტიდან</span></div><div className="vertical-label">LEARN. DISCOVER. BECOME.</div><div className="floating-card"><span className="orange-icon"><BookOpen size={27}/></span><div><strong>მეტი, ვიდრე გაკვეთილი</strong><small>საკუთარი თავის აღმოჩენის ადგილი</small></div></div></div></section>
 <div className="values-strip"><div className="wrap"><span><BookOpen/> ცოდნა, რომელიც გამოგადგება</span><span><Users/> გარემო, სადაც გისმენენ</span><span><Sparkles/> შესაძლებლობა, იყო შენ</span></div></div>
 <section className="section wrap about-section" id="about"><div><div className="eyebrow">გაიცანი აისი</div><Heading level={2}>სკოლა იწყება<br/>ბავშვის <em>ინტერესით.</em></Heading></div><div><p className="lead">კარგი განათლება კითხვების დასმის გამბედაობას გვაძლევს.</p><p>ახალი აისის ხედვა აერთიანებს სწავლას, აღმოჩენასა და თანამშრომლობას. სკოლასა და ოჯახს შორის კავშირი კი ბავშვის ყოველდღიურობის ბუნებრივი ნაწილია.</p><small>შემოთავაზებული ბრენდის ხედვა</small></div></section>
 <section id="learning" className="section learning-section"><div className="wrap"><div className="section-head"><div><div className="eyebrow">სწავლა და განვითარება</div><Heading level={2}>ყოველ ეტაპს — თავისი აღმოჩენა.</Heading></div><span className="section-index">01 — 03</span></div><div className="program-grid">{[{n:'01',title:'პირველი ნაბიჯები',grade:'დაწყებითი საფეხური',body:'კითხვის სიხარული, პირველი აღმოჩენები და სწავლის სიყვარული.',color:'peach'},{n:'02',title:'ინტერესების აღმოჩენა',grade:'საბაზო საფეხური',body:'კითხვებიდან იდეებამდე — მეტი დამოუკიდებლობა და თანამშრომლობა.',color:'blue'},{n:'03',title:'საკუთარი გზა',grade:'საშუალო საფეხური',body:'გაცნობიერებული არჩევანი და მომავლისთვის მზადება.',color:'green'}].map(p=><button key={p.n} className={`program-card ${p.color}`} onClick={()=>open(p.title)}><div className="program-top"><span>{p.n}</span><ArrowUpRight/></div><small>{p.grade}</small><Heading level={3}>{p.title}</Heading><p>{p.body}</p><span className="card-link">გაიგე მეტი <ArrowRight size={18}/></span></button>)}</div></div></section>
 <section className="section wrap portal-promo"><div><div className="eyebrow light">ჩემი აისი</div><Heading level={2}>სკოლის დღე.<br/>ერთი შეხედვით.</Heading><p>განრიგი, სასწავლო მასალები და მნიშვნელოვანი ამბები — მშობლისა და მოსწავლის პირად სივრცეში.</p><button className="white-button" onClick={switchMode}>ნახე პორტალის კონცეფცია <ArrowUpRight size={18}/></button></div><div className="mini-app"><div className="mini-top"><Logo/><span className="avatar">ნ</span></div><Heading level={3}>დილა მშვიდობისა, ნიკა ☀</Heading><p>ხუთშაბათი, 10 სექტემბერი · დემო</p><div className="mini-lesson"><span className="orange-icon"><BookOpen/></span><div><strong>მათემატიკა</strong><small>შემდეგი გაკვეთილი · 10:00</small></div><ChevronRight/></div><div className="mini-stats"><span><strong>4</strong>გაკვეთილი დღეს</span><span><strong>2</strong>ახალი დავალება</span></div></div></section>
 <section id="life" className="section wrap"><div className="section-head"><div><div className="eyebrow">სასკოლო ცხოვრება</div><Heading level={2}>დღეები, რომლებიც გვზრდის.</Heading></div><span className="caption">კონტენტის კონცეფციები</span></div><div className="stories"><button onClick={()=>open('აღმოჩენების დღე')}><span className="story-symbol">✳</span><small>შემეცნება</small><Heading level={3}>ერთი კითხვა, ბევრი აღმოჩენა</Heading><p>პროექტების, ექსპერიმენტებისა და ახალი იდეების ამბები.</p><ArrowUpRight/></button><button onClick={()=>open('ერთად შექმნილი ამბები')}><span className="story-symbol">↗</span><small>საზოგადოება</small><Heading level={3}>ერთად მეტს ვქმნით</Heading><p>მოსწავლეების ინიციატივები და სკოლის ყოველდღიურობა.</p><ArrowUpRight/></button></div></section>
 <section id="contact" className="contact-section"><div className="wrap"><div><div className="eyebrow">შემდეგი ნაბიჯი</div><Heading level={2}>გავიცნოთ ერთმანეთი.</Heading><p>აირჩიეთ დრო სკოლასთან სასაუბროდ.</p></div><button className="primary" onClick={()=>open('ვიზიტის დაგეგმვა')}>დაგეგმე ვიზიტი <ArrowUpRight size={20}/></button></div></section></main><footer className="wrap footer"><Logo/><span>აისი — ყოველი დღე ახალი დასაწყისია.</span><a href="https://aisi.edu.ge" target="_blank" rel="noreferrer">არსებული ვებგვერდი ↗</a><small>ვიზუალური პროტოტიპი · ფორმები მონაცემებს არ აგზავნის</small></footer></>:<>
 <header className="portal-header"><button className="logo-button" aria-label="საჯარო ვებგვერდზე დაბრუნება" onClick={switchMode}><Logo/></button><div className="portal-header-right"><span className="demo-pill">დემო მონაცემები</span><button className="icon-button" aria-label="შეტყობინებები" onClick={()=>open('შეტყობინებები')}><Bell size={21}/></button><span className="avatar">{role===roles[0]?'მ':role===roles[1]?'ნ':role===roles[2]?'ა':'ად'}</span></div></header>
 <SidebarProvider className="portal-layout"><Sidebar collapsible="none" className="portal-sidebar"><SidebarContent><SidebarGroup><div className="role-picker"><span>სივრცის დათვალიერება</span><Picker value={role} values={roles} onChange={changeRole} label="პორტალის როლი"/></div><SidebarMenu>{currentNavs.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={tab===n.id} onClick={()=>navigate(n.id)}><n.icon size={20}/>{n.label}</SidebarMenuButton></SidebarMenuItem>)}{role===roles[2]&&<SidebarMenuItem><SidebarMenuButton isActive={tab==='class'} onClick={()=>navigate('class')}><Users/>კლასის ჟურნალი</SidebarMenuButton></SidebarMenuItem>}{role===roles[3]&&<SidebarMenuItem><SidebarMenuButton isActive={tab==='settings'} onClick={()=>navigate('settings')}><Settings2/>სკოლის ბრენდი</SidebarMenuButton></SidebarMenuItem>}</SidebarMenu><div className="sidebar-bottom"><ShieldCheck size={27}/><strong>შენი სკოლის სივრცე</strong><p>სწავლისთვის.<br/>კავშირისთვის.<br/>ყოველი ახალი დღისთვის.</p><button className="text-link" onClick={switchMode}>ვებგვერდზე დაბრუნება <ArrowUpRight size={16}/></button></div></SidebarGroup></SidebarContent></Sidebar>
 <main id="main" className="portal-main"><div className="mobile-role"><Picker value={role} values={roles} onChange={changeRole} label="პორტალის როლი მობილურზე"/>{(role===roles[2]||role===roles[3])&&<button className="outline" onClick={()=>navigate(role===roles[2]?'class':'settings')}>{role===roles[2]?'ჟურნალი':'ბრენდი'}</button>}</div><div className="dashboard-heading"><div><div className="eyebrow">ჩემი აისი / {role}</div><Heading level={1}>{tab==='home'?(role===roles[0]?'დილა მშვიდობისა, მარიამ':role===roles[1]?'კარგი დღე, ნიკა':role===roles[2]?'კარგი დღე, ანა':'სკოლა ერთი შეხედვით'):tab==='schedule'?'სასწავლო განრიგი':tab==='library'?'ჩემი ბიბლიოთეკა':tab==='payments'?'გადახდები':tab==='class'?'კლასის ჟურნალი':'შენი სკოლა. შენი ბრენდი.'}{tab==='home'&&<Sun className="sun"/>}</Heading><p>ხუთშაბათი, 10 სექტემბერი, 2026</p></div>{role===roles[0]&&<div className="child-picker"><span className="avatar small">{child[0]}</span><Picker value={child} values={['ნიკა','ელენე']} onChange={setChild} label="ბავშვის არჩევა"/><small>{child==='ნიკა'?'VI':'III'} კლასი</small></div>}</div>
 {tab==='home'&&<><div className="dashboard-grid"><section className="day-card"><div className="eyebrow light">{role===roles[0]?`${child}ს დღე`:role===roles[3]?'დღის შეჯამება':'დღის გეგმა'}</div><Heading level={2}>{role===roles[3]?'ყველაფერი იწყება კარგი დღით.':'ახალი დღე, ახალი შესაძლებლობები.'}</Heading><p>{role===roles[3]?'განრიგი, დასწრება და მიმდინარე მოთხოვნები ერთ სივრცეში.':'გაკვეთილები იწყება 09:00-ზე. მოემზადე პირველი აღმოჩენისთვის.'}</p><button className="white-button" onClick={()=>navigate('schedule')}>დღის განრიგი <ArrowRight size={18}/></button></section><section className="panel next-event"><div className="panel-heading"><span>ყურადღების ცენტრში</span><CalendarDays size={18}/></div><span className="event-date">15 <small>სექ</small></span><Heading level={3}>მშობელთა შეხვედრა</Heading><p>18:00 · შეხვედრების სივრცე</p><button className="text-link" onClick={()=>open('მშობელთა შეხვედრა')}>დეტალების ნახვა <ArrowRight size={17}/></button></section></div>
 <div className="stat-grid">{[{icon:CalendarDays,value:role===roles[3]?'24':String(dayLessons.length),label:role===roles[3]?'კლასი':'გაკვეთილი დღეს',tone:'blue'},{icon:BookOpen,value:role===roles[3]?'8':'2',label:role===roles[3]?'ახალი განაცხადი':'მიმდინარე დავალება',tone:'peach'},{icon:Check,value:role===roles[3]?'94%':student==='ელენე'?'98%':'96%',label:'დასწრება · სექტემბერი',tone:'green'},{icon:financial?CreditCard:GraduationCap,value:financial?(student==='ელენე'?'400 ₾':'450 ₾'):'3',label:financial?'შემდეგი გადასახადი':'სასწავლო რესურსი',tone:'blue'}].map(s=><section className="stat-card" key={s.label}><span className={`stat-icon ${s.tone}`}><s.icon size={21}/></span><strong>{s.value}</strong><p>{s.label}</p></section>)}</div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><Heading level={3}>დღევანდელი გაკვეთილები</Heading><button className="text-link" onClick={()=>navigate('schedule')}>სრულად <ArrowUpRight size={17}/></button></div>{dayLessons.slice(0,3).map((l,i)=><div className="lesson-row" key={l.name}><time>{l.time}</time><span className={`lesson-line line-${i}`}/><div><strong>{l.name}</strong><small>{l.room} · {l.teacher}</small></div><span className="lesson-duration">45 წთ</span></div>)}</section><section className="panel"><div className="panel-heading"><Heading level={3}>სკოლის ამბები</Heading><Bell size={18}/></div><button className="notice" onClick={()=>open('ბიბლიოთეკის ახალი რესურსები')}><span className="notice-tag">ბიბლიოთეკა</span><Heading level={4}>ახალი ისტორიების დროა</Heading><p>აღმოაჩინე შენი კლასის სასწავლო მასალები.</p><small>დღეს · 08:30</small></button><button className="notice" onClick={()=>open('სექტემბრის კალენდარი')}><span className="notice-tag teal">ღონისძიებები</span><Heading level={4}>შენი სექტემბრის კალენდარი</Heading><small>გუშინ · 16:00</small></button></section></div>
 <section className="panel attendance-chart"><div className="panel-heading"><Heading level={3}>დასწრების ტენდენცია</Heading><span className="caption">კვირის საჩვენებელი მაჩვენებლები</span></div><div className="chart-bars" role="img" aria-label="დასწრება: ორშაბათი 94, სამშაბათი 97, ოთხშაბათი 95, ხუთშაბათი 98, პარასკევი 96 პროცენტი">{[94,97,95,98,96].map((v,i)=><div key={i}><span>{v}%</span><div className="bar-track"><i style={{height:`${v}%`}}/></div><small>{['ორშ','სამ','ოთხ','ხუთ','პარ'][i]}</small></div>)}</div></section></>}
 {tab==='schedule'&&<section className="panel"><div className="day-switch" aria-label="დღის არჩევა">{['ორშ 07','სამ 08','ოთხ 09','ხუთ 10','პარ 11'].map((d,i)=><button key={d} className={day===i?'selected':''} aria-pressed={day===i} onClick={()=>setDay(i)}>{d}</button>)}</div><div className="panel-heading"><Heading level={3}>{['ორშაბათის','სამშაბათის','ოთხშაბათის','ხუთშაბათის','პარასკევის'][day]} განრიგი</Heading><span className="demo-pill">საჩვენებელი კვირა</span></div>{dayLessons.map((l,i)=><div className="lesson-row large" key={l.name}><time>{l.time}</time><span className={`lesson-line line-${i%3}`}/><div><strong>{dayLessons[(i+day+dayLessons.length-3)%dayLessons.length].name}</strong><small>{l.teacher} · {l.room}</small></div><span className="lesson-duration">45 წუთი</span></div>)}</section>}
 {tab==='library'&&<><label className="search-box"><Search size={20}/><input aria-label="წიგნის ძიება" value={query} onChange={e=>setQuery(e.target.value)} placeholder="მოძებნე წიგნი ან საგანი"/></label><div className="book-grid">{['ქართული ენა','მათემატიკა','ინგლისური ენა'].filter(b=>b.includes(query.trim())).map((b,i)=><button className="panel book-card" key={b} onClick={()=>open(b+' — სასწავლო მასალა')}><div className={`book-cover cover-${i}`}><BookOpen size={36}/><Heading level={3}>{b}</Heading><span>{student==='ელენე'?'III':'VI'} კლასი</span></div><Heading level={3}>{b}</Heading><p>რესურსის საჩვენებელი ბარათი</p><span className="text-link">მასალის ნახვა <ArrowUpRight size={16}/></span></button>)}</div>{!['ქართული ენა','მათემატიკა','ინგლისური ენა'].some(b=>b.includes(query.trim()))&&<Empty className="panel"><EmptyHeader><Search/><EmptyTitle>რესურსი ვერ მოიძებნა</EmptyTitle><EmptyDescription>სცადე სხვა საგნის სახელით ძებნა.</EmptyDescription></EmptyHeader><button className="outline" onClick={()=>setQuery('')}>ძიების გასუფთავება</button></Empty>}</>}
 {tab==='payments'&&financial&&<><div className="payment-banner"><div><span>შემდეგი გადასახადი · {student}</span><Heading level={2}>{student==='ელენე'?'400':'450'}.00 ₾</Heading><p>სწავლის საფასური · 15 სექტემბრამდე</p></div><button className="primary" onClick={()=>open('გადახდის დეტალები')}>გადახდის ნახვა <ArrowUpRight size={18}/></button></div><section className="panel"><Heading level={3}>გადახდების ისტორია</Heading><Table><TableHeader><TableRow><TableHead>დანიშნულება</TableHead><TableHead>თარიღი</TableHead><TableHead>თანხა</TableHead><TableHead>სტატუსი</TableHead></TableRow></TableHeader><TableBody>{['სექტემბერი','აგვისტო','ივლისი'].map((m,i)=><TableRow key={m}><TableCell>სწავლის საფასური · {m}</TableCell><TableCell>15.0{9-i}.2026</TableCell><TableCell>{student==='ელენე'?'400':'450'} ₾</TableCell><TableCell><span className={i===0?'status pending':'status'}>{i===0?'მოსალოდნელი':'გადახდილი'}</span></TableCell></TableRow>)}</TableBody></Table></section></>}
 {tab==='class'&&<section className="panel"><div className="panel-heading"><Heading level={3}>VI კლასი · ქართული ენა</Heading><span className="demo-pill">საჩვენებელი ჩანაწერები</span></div><p>დასწრების მონიშვნა — ცვლილება მხოლოდ ამ ეკრანზე აისახება.</p><Table><TableHeader><TableRow><TableHead>მოსწავლე</TableHead><TableHead>დასწრება</TableHead></TableRow></TableHeader><TableBody>{['მოსწავლე 01','მოსწავლე 02','მოსწავლე 03','მოსწავლე 04'].map(n=><AttendanceRow key={n} name={n}/>)}</TableBody></Table></section>}
 {tab==='settings'&&<section className="panel brand-settings"><span className="stat-icon peach"><Settings2/></span><Heading level={2}>პლატფორმა იცვლის ფერს.<br/>სკოლა ინარჩუნებს ხასიათს.</Heading><p>სახელი, ლოგო, ფერები და დომენი მომავალი პლატფორმის პარამეტრებიდან იმართება. აქ შეგიძლიათ ფერის ცვლილების დათვალიერება.</p><div className="theme-options"><button aria-pressed={!theme} onClick={()=>setTheme(false)}><span style={{background:'#F5683C'}}/>აისი · მზისფერი</button><button aria-pressed={theme} onClick={()=>setTheme(true)}><span style={{background:'#087F8C'}}/>ალტერნატივა · ფირუზისფერი</button></div><div className="brand-preview"><Logo/><span>aisi.edu.ge</span></div></section>}
 <p className="portal-footnote">დიზაინის პროტოტიპი · სახელები, განრიგი, თანხები და სტატისტიკა გამოგონილი დემო მონაცემებია.</p></main></SidebarProvider><nav className="bottom-nav" aria-label="მობილური პორტალის ნავიგაცია">{currentNavs.map(n=><button key={n.id} aria-current={tab===n.id?'page':undefined} className={tab===n.id?'active':''} onClick={()=>navigate(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}</nav></>}
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog('')}}><DialogContent className="concept-dialog"><DialogTitle>{dialog}</DialogTitle><DialogDescription>{dialog==='ვიზიტის დაგეგმვა'?'გაიცანი სკოლა და დასვი შენთვის მნიშვნელოვანი კითხვები.':'აისის ახალი გამოცდილება · საჩვენებელი კონცეფცია'}</DialogDescription>{dialog==='ვიზიტის დაგეგმვა'?(sent?<div className="success"><Check/><Heading level={3}>ვიზიტის სცენარი დასრულებულია</Heading><p>ეს დემო ფორმაა. ინფორმაცია არ შენახულა და სკოლაში არ გაგზავნილა.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>სახელი<input required autoComplete="off" placeholder="საჩვენებელი სახელი"/></label><label>ელფოსტა<input type="email" required autoComplete="off" placeholder="name@example.com"/></label><label>სასურველი თარიღი<input type="date" required/></label><p className="caption">დემო ფორმა — გამოიყენეთ გამოგონილი ინფორმაცია. მონაცემები არსად იგზავნება.</p><button className="primary" type="submit">დემო მოთხოვნის დასრულება <ArrowRight size={18}/></button></form>):dialog==='გადახდის დეტალები'?<div><div className="payment-detail"><span>სწავლის საფასური · {student}</span><strong>{student==='ელენე'?'400':'450'}.00 ₾</strong><span>გადახდის ვადა: 15 სექტემბერი, 2026</span></div><p>სამუშაო პლატფორმაში აქ გაიხსნება ბანკის დაცული გადახდის გვერდი. პროტოტიპში გადახდა არ სრულდება.</p></div>:<div className="detail-content"><BookOpen size={30}/><p>{dialog==='შეტყობინებები'?'15 სექტემბრის მშობელთა შეხვედრა და ბიბლიოთეკის ახალი რესურსები — თქვენი დღის ორი სიახლე.':dialog.includes('მასალა')?'აქ გამოჩნდება რესურსის აღწერა, ავტორი, შესაბამისი კლასი და წაკითხვის ან ჩამოტვირთვის უფლება. ამ პროტოტიპს წიგნის ფაილი არ ახლავს.':dialog==='მშობელთა შეხვედრა'?'15 სექტემბერი · 18:00. სასწავლო გეგმები და მშობელსა და სკოლას შორის კომუნიკაცია. თარიღი და შეხვედრა საჩვენებელია.':dialog==='პირველი ნაბიჯები'?'სწავლის ინტერესის გაღვივება, წიგნთან მეგობრობა და ურთიერთობის უნარები. კონკრეტულ საგნებსა და პროგრამას სკოლა დაადასტურებს.':dialog==='ინტერესების აღმოჩენა'?'საგნობრივი ცოდნის გაღრმავება, პროექტები და თანამშრომლობა. პროგრამის საბოლოო შინაარსი სკოლის მიერ დამტკიცდება.':dialog==='საკუთარი გზა'?'კრიტიკული აზროვნება, დამოუკიდებელი მუშაობა და მომავალი არჩევანისთვის მზადება. საბოლოო პროგრამა საჭიროებს სკოლის დადასტურებას.':'ეს სივრცე დაეთმობა სკოლის მიერ დამტკიცებულ აღწერას, თარიღებსა და საჭირო ინფორმაციას. ნაჩვენებია კონტენტის კონცეფცია.'}</p><button className="outline" onClick={()=>setDialog('')}>გასაგებია <Check size={17}/></button></div>}</DialogContent></Dialog></div>
}
function AttendanceRow({name}:{name:string}){const [value,setValue]=useState('ესწრება');return <TableRow><TableCell>{name}</TableCell><TableCell><Picker label={name+' დასწრება'} value={value} values={['ესწრება','არ ესწრება','დაგვიანება']} onChange={setValue}/></TableCell></TableRow>}


function Heading({level=2,children,...props}:HTMLAttributes<HTMLHeadingElement>&{level?:1|2|3|4}){
 return createElement(`h${level}`,props,children);
}
