'use client';
import {useState} from 'react';
import {FileText,FolderOpen,Search,History,Check,Plus,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import './documents.css';
type State='draft'|'review'|'approved'|'returned';
type Doc={id:number;title:string;folder:string;state:State;version:number;owner:string;body:string;history:string[]};
const labels:Record<State,string>={draft:'მონახაზი',review:'განსახილველი',approved:'დამტკიცებული',returned:'დაბრუნებული'};
const sample:Doc[]=[
 {id:1,title:'VI კლასის სასწავლო გეგმა',folder:'სასწავლო გეგმები',state:'draft',version:1,owner:'მასწავლებელი',body:'საჩვენებელი სამუშაო გეგმა\n\nმიზანი: მოსწავლეებმა ისწავლონ ინფორმაციის მოძიება და წყაროების შეფასება.\nაქტივობა: მცირე ჯგუფის პროექტი.\nშეფასება: პროექტის განხილვა და უკუკავშირი.',history:['v1 · მასწავლებელმა შექმნა მონახაზი']},
 {id:2,title:'პროექტის კვირის პროგრამა',folder:'პროექტები',state:'review',version:2,owner:'მასწავლებელი',body:'საჩვენებელი პროგრამა\n\nპროექტების კვირა: იდეის შერჩევა, კვლევა, გუნდური მუშაობა და წარდგენა.\nგასარკვევია ოთახების განაწილება.\nეს არ არის სკოლის მოქმედი პროგრამა.',history:['v1 · შეიქმნა სამუშაო პროგრამა','v2 · დაემატა აქტივობების აღწერა','v2 · გაგზავნილია დირექტორთან']},
 {id:3,title:'დოკუმენტის მომზადების გზამკვლევი',folder:'სკოლის წესები',state:'approved',version:1,owner:'დირექტორი',body:'საჩვენებელი გზამკვლევი\n\n1. მიუთითეთ დოკუმენტის მიზანი და პასუხისმგებელი.\n2. შეინარჩუნეთ ვერსიების ისტორია.\n3. დამტკიცებისთვის გაგზავნეთ საბოლოო სამუშაო ვერსია.\n\nეს არის დემო ტექსტი.',history:['v1 · დირექტორმა დაამტკიცა დემო გზამკვლევი']},
];
export default function DocumentCenter({role}:{role:string}){
 const [docs,setDocs]=useState<Doc[]>(sample),[folder,setFolder]=useState('ყველა'),[filter,setFilter]=useState('ყველა'),[query,setQuery]=useState(''),[selected,setSelected]=useState<number|null>(null),[mode,setMode]=useState<'preview'|'history'|'edit'|'new'>('preview'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[note,setNote]=useState(''),[feedback,setFeedback]=useState('');
 const director=role==='დირექტორი',teacher=role==='მასწავლებელი';
 const current=docs.find(d=>d.id===selected);
 const folders=['ყველა','სასწავლო გეგმები','პროექტები','სკოლის წესები'];
 const list=docs.filter(d=>(folder==='ყველა'||d.folder===folder)&&(filter==='ყველა'||labels[d.state]===filter)&&d.title.includes(query.trim()));
 const show=(d:Doc,next:'preview'|'history'|'edit')=>{setSelected(d.id);setMode(next);setTitle(d.title);setBody(d.body);setNote('');setFeedback('')};
 const change=(state:State)=>{if(!current)return;const event=state==='review'?'მასწავლებელმა გაგზავნა განსახილველად':state==='approved'?'დირექტორმა დაამტკიცა':`დირექტორმა დააბრუნა: ${note.trim()}`;setDocs(prev=>prev.map(d=>d.id===current.id?{...d,state,history:[...d.history,`v${d.version} · ${event}`]}:d));setFeedback('ცვლილება აისახა დემოში.');setNote('')};
 const save=()=>{if(!title.trim()||!body.trim())return;if(mode==='new'){const id=Math.max(...docs.map(d=>d.id))+1;setDocs(prev=>[...prev,{id,title:title.trim(),body:body.trim(),folder:'სასწავლო გეგმები',state:'draft',version:1,owner:'მასწავლებელი',history:['v1 · მასწავლებელმა შექმნა მონახაზი']}]);setSelected(id)}else if(current){setDocs(prev=>prev.map(d=>d.id===current.id?{...d,title:title.trim(),body:body.trim(),state:'draft',version:d.version+1,history:[...d.history,`v${d.version+1} · შენახულია ახალი სამუშაო ვერსია`]}:d))}setMode('preview');setFeedback('მონახაზი შენახულია მხოლოდ მიმდინარე დემოში.')};
 return <section className="doc-center"><div className="doc-heading"><div><div className="eyebrow">მასწავლებლებისა და ხელმძღვანელობის სივრცე</div><h2>ერთი ადგილი. დოკუმენტის სრული გზა.</h2><p>გეგმები, პროექტები, განხილვა და დამტკიცება.</p></div>{teacher&&<button className="primary" onClick={()=>{setMode('new');setSelected(null);setTitle('');setBody('');setFeedback('')}}><Plus size={18}/>ახალი მონახაზი</button>}</div><div className="doc-demo"><ShieldCheck size={20}/><p>ყველა დოკუმენტი გამოგონილია. აქ შეყვანილი ტექსტი სერვერზე არ იგზავნება. თანამშრომლის როლის შეცვლით შეგიძლია ერთი მოთხოვნის მთელი გზა ნახო.</p></div><div className="doc-stats">{(['draft','review','approved'] as State[]).map(s=><button key={s} aria-pressed={filter===labels[s]} onClick={()=>setFilter(filter===labels[s]?'ყველა':labels[s])}><strong>{docs.filter(d=>d.state===s).length}</strong><span>{labels[s]}</span></button>)}</div><div className="doc-workspace"><aside className="doc-folders" aria-label="დოკუმენტების საქაღალდეები">{folders.map(f=><button key={f} aria-pressed={folder===f} onClick={()=>setFolder(f)}><FolderOpen size={18}/>{f}</button>)}<div className="doc-access"><strong>შენი წვდომა</strong><p>{director?'განხილვა და დამტკიცება':teacher?'მონახაზი და გაგზავნა':'შიდა დოკუმენტების დათვალიერება'}</p><small>ეს UI დემოა; რეალური უფლებები Laravel-ში მოწმდება.</small></div></aside><div className="panel doc-list"><label className="search-box"><Search size={18}/><input aria-label="დოკუმენტის ძიება" placeholder="მოძებნე დოკუმენტი" value={query} onChange={e=>setQuery(e.target.value)}/></label>{filter!=='ყველა'&&<button className="text-link" onClick={()=>setFilter('ყველა')}>ფილტრი: {filter} · გასუფთავება ×</button>}<Table><TableHeader><TableRow><TableHead>დოკუმენტი</TableHead><TableHead>სტატუსი</TableHead><TableHead>ვერსია</TableHead><TableHead>ისტორია</TableHead></TableRow></TableHeader><TableBody>{list.map(d=><TableRow key={d.id}><TableCell><button className="doc-title" onClick={()=>show(d,'preview')}><FileText size={19}/><span>{d.title}<small>{d.folder} · {d.owner}</small></span></button></TableCell><TableCell><span className={`doc-status ${d.state}`}>{labels[d.state]}</span></TableCell><TableCell>v{d.version}</TableCell><TableCell><button className="icon-button" aria-label={`${d.title} — ისტორია`} onClick={()=>show(d,'history')}><History size={18}/></button></TableCell></TableRow>)}</TableBody></Table>{list.length===0&&<div className="doc-empty"><p>დოკუმენტი ვერ მოიძებნა.</p><button className="text-link" onClick={()=>{setQuery('');setFolder('ყველა');setFilter('ყველა')}}>ფილტრების გასუფთავება</button></div>}</div></div>
 <Dialog open={selected!==null||mode==='new'} onOpenChange={v=>{if(!v){setSelected(null);setMode('preview')}}}><DialogContent className="concept-dialog doc-dialog"><DialogTitle>{mode==='new'?'ახალი სამუშაო მონახაზი':current?.title}</DialogTitle><DialogDescription>{mode==='history'?'ვერსიებისა და გადაწყვეტილებების ისტორია':'შიდა დოკუმენტის საჩვენებელი სამუშაო პროცესი'}</DialogDescription>{mode==='new'||mode==='edit'?<form onSubmit={e=>{e.preventDefault();save()}}><label>სათაური<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>დემო შინაარსი<textarea required maxLength={8000} value={body} onChange={e=>setBody(e.target.value)} placeholder="მხოლოდ გამოგონილი სამუშაო ტექსტი"/></label><button className="primary" type="submit">მონახაზის შენახვა</button></form>:current&&mode==='history'?<ol className="doc-history">{current.history.map((event,i)=><li key={i}><History size={16}/><span>{event}</span></li>)}</ol>:current&&<><div className="doc-meta"><span className={`doc-status ${current.state}`}>{labels[current.state]}</span><span>v{current.version}</span><span>{current.folder}</span></div><div className="doc-paper">{current.body}</div>{teacher&&current.owner==='მასწავლებელი'&&(current.state==='draft'||current.state==='returned')&&<div className="service-actions"><button className="outline" onClick={()=>show(current,'edit')}>ახალი ვერსიის მომზადება</button><button className="primary" onClick={()=>change('review')}>დირექტორთან გაგზავნა</button></div>}{director&&current.state==='review'&&<div className="doc-decision"><label>შენიშვნა დაბრუნებისთვის<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="მიუთითე, რა არის შესასწორებელი"/></label><div className="service-actions"><button className="primary" onClick={()=>change('approved')}><Check size={17}/>დამტკიცება</button><button className="outline" disabled={!note.trim()} onClick={()=>change('returned')}>შესასწორებლად დაბრუნება</button></div></div>}{current.state==='approved'&&<p className="caption">ეს ვერსია დამტკიცებულია. მისი ჩუმად გადაწერა დაუშვებელია.</p>}<button className="text-link" onClick={()=>setMode('history')}><History size={17}/>ვერსიებისა და განხილვის ისტორია</button></>}{feedback&&<p className="doc-feedback" role="status">{feedback}</p>}</DialogContent></Dialog></section>
}
