'use client';
import {useState} from 'react';
import {CalendarDays,Check,Users,ClipboardList} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './services.css';
export default function SchoolServices({role,child}:{role:string;child:string}){
 const [booking,setBooking]=useState(''),[club,setClub]=useState(''),[consent,setConsent]=useState('pending'),[absent,setAbsent]=useState(''),[meetingOpen,setMeetingOpen]=useState(false),[date,setDate]=useState('2026-09-17'),[review,setReview]=useState('მოლოდინში');
 const staff=role==='მასწავლებელი'||role==='ადმინისტრაცია'||role==='დირექტორი';
 const parent=role==='მშობელი';
 const pending=(parent&&consent==='pending'?1:0)+(booking?0:1);
 return <section className="school-services"><div className="service-intro"><div><span className="eyebrow">სკოლა და ოჯახი — უფრო ახლოს</span><h2>{staff?'ნაკლები რუტინა. მეტი ყურადღება.':'შენი შემდეგი ნაბიჯი — აქ არის.'}</h2><p>შეხვედრები, კლუბები და მოთხოვნები ერთ სივრცეში.</p></div><span className="demo-pill">ინტერაქტიული დემო</span></div><div role="status" className="service-summary"><ClipboardList size={22}/><span>{staff?'მოთხოვნების დემო სამუშაო სია':`${child} · ${pending} მოქმედება ყურადღებისთვის`}</span><small>ცვლილებები დროებითია; სკოლაში არაფერი იგზავნება.</small></div>
 <div className="service-grid"><section className="panel"><span className="stat-icon blue"><CalendarDays/></span><h3>შეხვედრა მასწავლებელთან</h3><p>მარიამ კ. · ქართული ენა<br/>17 სექტემბერი · ინდივიდუალური საუბარი</p>{booking?<div className="service-result" role="status"><Check size={18}/><span>{booking} · დემო ჯავშანი</span><button className="text-link" onClick={()=>setBooking('')}>გაუქმება</button></div>:<button className="primary" onClick={()=>setMeetingOpen(true)}>აირჩიე დრო</button>}<small>მხოლოდ თავისუფალი დროები · 15 წუთი</small></section>
 <section className="panel"><span className="stat-icon green"><Users/></span><h3>კლუბები და ინტერესები</h3><p>აღმოაჩინე აქტივობა სკოლის შემდეგ.</p><div className="club-options">{[{name:'რობოტიკა',time:'სამშაბათი · 15:00',full:false},{name:'დებატები',time:'ხუთშაბათი · 15:00',full:true}].map(c=><div key={c.name}><div><strong>{c.name}</strong><small>{c.time} · {c.full?'ადგილები შევსებულია':'2 თავისუფალი ადგილი'}</small></div><button className="outline" disabled={club===c.name} onClick={()=>setClub(c.name)}>{club===c.name?'არჩეულია':c.full?'მოლოდინის სია':'ჩაწერა'}</button></div>)}</div>{club&&<div className="service-result" role="status"><span>{club==='დებატები'?'დაემატა მოლოდინის სიას':'კლუბში დემო ჩაწერა შესრულდა'} · {club}</span><button className="text-link" onClick={()=>setClub('')}>გაუქმება</button></div>}</section>
 {parent&&<section className="panel"><span className="stat-icon peach"><ClipboardList/></span><h3>მშობლის თანხმობა</h3><p><strong>სასწავლო ვიზიტი მუზეუმში</strong><br/>22 სექტემბერი · 10:00–13:00<br/>სკოლის ჯგუფი, მასწავლებლის თანხლებით.</p><p className="caption">საჩვენებელი ღონისძიებაა. რეალურ სისტემაში აქ იქნება ზუსტი პროგრამა, ტრანსპორტი, პასუხისმგებელი და პირობების ვერსია.</p>{consent==='pending'?<div className="service-actions"><button className="primary" onClick={()=>setConsent('accepted')}>ვეთანხმები</button><button className="outline" onClick={()=>setConsent('declined')}>უარი</button></div>:<div className="service-result" role="status"><span>{consent==='accepted'?'თანხმობა':'უარი'} დაფიქსირდა მხოლოდ დემოში.</span><button className="text-link" onClick={()=>setConsent('pending')}>შეცვლა</button></div>}</section>}
 {parent&&<section className="panel"><h3>გაცდენის შეტყობინება</h3><p>წინასწარ აცნობე სკოლას დაგეგმილი არყოფნის შესახებ.</p>{absent?<div className="service-result" role="status"><span>{absent} · მოთხოვნის დემო სტატუსი: მოლოდინში</span><button className="text-link" onClick={()=>setAbsent('')}>გაუქმება</button></div>:<form onSubmit={e=>{e.preventDefault();setAbsent(date)}}><label>გაცდენის თარიღი<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><p className="caption">ეს არ არის გაცდენის ავტომატური გამართლება. პირადი/სამედიცინო ინფორმაცია დემოში არ შეიყვანო.</p><button type="submit" className="primary">დემო მოთხოვნის შექმნა</button></form>}</section>}
 {staff&&<section className="panel"><h3>გაცდენის მოთხოვნების განხილვა</h3><p>მოსწავლე 01 · VI კლასი<br/>17 სექტემბერი · ოჯახის წინასწარი შეტყობინება</p><div className="service-result" role="status">სტატუსი: {review}</div><div className="service-actions"><button className="primary" disabled={review!=='მოლოდინში'} onClick={()=>setReview('დადასტურებული')}>დადასტურება</button><button className="outline" disabled={review!=='მოლოდინში'} onClick={()=>setReview('უარყოფილი')}>უარი</button>{review!=='მოლოდინში'&&<button className="text-link" onClick={()=>setReview('მოლოდინში')}>დემოს აღდგენა</button>}</div><small>ეს ფიქციური მოთხოვნაა; სხვა როლის რეალურ ჩანაწერს არ უკავშირდება.</small></section>}
 </div><Dialog open={meetingOpen} onOpenChange={setMeetingOpen}><DialogContent className="concept-dialog"><DialogTitle>აირჩიე შეხვედრის დრო</DialogTitle><DialogDescription>17 სექტემბერი · მარიამ კ. · ყველა დრო საჩვენებელია</DialogDescription><div className="meeting-slots">{['16:00','16:15','16:30','16:45'].map(t=><button key={t} disabled={t==='16:15'} className="outline" onClick={()=>{setBooking(t);setMeetingOpen(false)}}>{t}{t==='16:15'?' · დაკავებულია':''}</button>)}</div><p>არჩევა ქმნის მხოლოდ დროებით დემო ჯავშანს.</p></DialogContent></Dialog></section>
}
