'use client';
import {useState} from 'react';
import {Logo} from '../AisiConcept';
import {Activity,ArrowLeft,ArrowRight,BarChart3,Bell,BookMarked,BriefcaseBusiness,Bus,CalendarDays,Check,ChevronRight,ClipboardCheck,Clock3,CreditCard,FileCheck2,GraduationCap,HeartPulse,LayoutDashboard,MessageSquareText,Palette,Plus,School,Search,ShieldCheck,Sparkles,Star,Users} from 'lucide-react';

type View='today'|'inbox'|'portfolio'|'progress'|'safety'|'health'|'teacher'|'substitute'|'admissions'|'operations'|'director'|'platform';
const modules:{id:View;label:string;audience:string;icon:any}[]=[
 {id:'today',label:'დღის ცენტრი',audience:'ოჯახი',icon:LayoutDashboard},
 {id:'inbox',label:'შეტყობინებები',audience:'ყველა',icon:MessageSquareText},
 {id:'portfolio',label:'პორტფოლიო',audience:'მოსწავლე',icon:BookMarked},
 {id:'progress',label:'პროგრესი და ტაბელი',audience:'ოჯახი',icon:BarChart3},
 {id:'safety',label:'გაყვანა და თანხმობა',audience:'მშობელი',icon:ShieldCheck},
 {id:'health',label:'ჯანმრთელობა',audience:'უფლებამოსილი',icon:HeartPulse},
 {id:'teacher',label:'მასწავლებლის სივრცე',audience:'მასწავლებელი',icon:GraduationCap},
 {id:'substitute',label:'ჩანაცვლება',audience:'ადმინისტრაცია',icon:Users},
 {id:'admissions',label:'მიღების CRM',audience:'მიღება',icon:BriefcaseBusiness},
 {id:'operations',label:'სერვისები',audience:'ოჯახი',icon:Bus},
 {id:'director',label:'სკოლის პულსი',audience:'დირექტორი',icon:Activity},
 {id:'platform',label:'პლატფორმის მართვა',audience:'Super admin',icon:Palette},
];

const lessons=[['09:00','ქართული ენა','ოთახი 204'],['10:00','მათემატიკა','ოთახი 208'],['11:00','ინგლისური','ოთახი 203'],['12:00','ბუნება','ლაბორატორია']];
const events=[['08:54','ნიკა სკოლაში გამოცხადდა','მთავარი შესასვლელი'],['09:00','ქართული ენის გაკვეთილი','დასწრება მონიშნულია'],['15:20','გაყვანის ნებართვა','თამარ მაისურაძე']];

export default function PlatformSuite(){
 const [view,setView]=useState<View>('today');
 const current=modules.find(x=>x.id===view)!;
 return <div className="suite-shell">
  <a className="skip" href="#suite-main">მთავარ შინაარსზე გადასვლა</a>
  <aside className="suite-side">
   <a href="/" className="suite-logo"><Logo/></a>
   <div className="suite-school"><span>სკოლის სივრცე</span><strong>აისი · 2026/27</strong></div>
   <nav aria-label="პლატფორმის მოდულები">{modules.map(m=><button key={m.id} className={view===m.id?'active':''} onClick={()=>setView(m.id)} aria-current={view===m.id?'page':undefined}><m.icon/><span><strong>{m.label}</strong><small>{m.audience}</small></span></button>)}</nav>
   <a className="suite-back" href="/"><ArrowLeft/> კონცეფციაზე დაბრუნება</a>
  </aside>
  <div className="suite-workspace">
   <header className="suite-top"><div><small>ხუთშაბათი · 11 სექტემბერი</small><strong>{current.label}</strong></div><div className="suite-top-actions"><button aria-label="ძიება"><Search/></button><button aria-label="შეტყობინებები" className="has-dot"><Bell/></button><span className="suite-avatar">ით</span></div></header>
   <nav className="suite-mobile-nav" aria-label="მოდულების მობილური ნავიგაცია">{modules.map(m=><button key={m.id} className={view===m.id?'active':''} onClick={()=>setView(m.id)}><m.icon/><span>{m.label}</span></button>)}</nav>
   <main id="suite-main" className="suite-main">
    <div className="suite-heading"><div><span className="suite-kicker">{current.audience}</span><h1>{current.label}</h1></div><span className="prototype-pill">ინტერაქტიული დიზაინი</span></div>
    {view==='today'&&<Today/>}{view==='inbox'&&<Inbox/>}{view==='portfolio'&&<Portfolio/>}{view==='progress'&&<Progress/>}{view==='safety'&&<Safety/>}{view==='health'&&<Health/>}{view==='teacher'&&<Teacher/>}{view==='substitute'&&<Substitute/>}{view==='admissions'&&<Admissions/>}{view==='operations'&&<Operations/>}{view==='director'&&<Director/>}{view==='platform'&&<Platform/>}
    <p className="suite-note">დიზაინის დემო · ნაჩვენები ადამიანები, თანხები და ჩანაწერები გამოგონილია.</p>
   </main>
  </div>
 </div>
}

function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={'suite-card '+className}>{children}</section>}
function SectionTitle({title,meta}:{title:string;meta?:string}){return <div className="suite-card-title"><h2>{title}</h2>{meta&&<span>{meta}</span>}</div>}
function Stat({label,value,detail,tone='blue'}:{label:string;value:string;detail:string;tone?:string}){return <Card className="suite-stat"><span className={'stat-mark '+tone}/><small>{label}</small><strong>{value}</strong><p>{detail}</p></Card>}
function Action({children}:{children:React.ReactNode}){return <button className="suite-primary">{children}<ArrowRight/></button>}

function Today(){return <><div className="today-banner"><div><span>დილა მშვიდობისა, ია</span><h2>დღეს სამი საკითხი<br/>ითხოვს ყურადღებას.</h2><p>ყველაფერი, რაც ნიკას დღისთვის მნიშვნელოვანია — ერთ ადგილზე.</p></div><div className="today-count"><strong>3</strong><span>შესასრულებელი</span></div></div><div className="suite-grid two"><Card><SectionTitle title="დღის მოქმედებები" meta="3 დარჩა"/><div className="action-list"><button><span className="task-icon orange"><FileCheck2/></span><span><strong>ექსკურსიის თანხმობა</strong><small>პასუხი საჭიროა 14 სექტემბრამდე</small></span><ChevronRight/></button><button><span className="task-icon navy"><CreditCard/></span><span><strong>სწავლის საფასური</strong><small>450 ₾ · ვადა 15 სექტემბერი</small></span><ChevronRight/></button><button><span className="task-icon green"><CalendarDays/></span><span><strong>მშობელთა შეხვედრა</strong><small>აირჩიეთ თავისუფალი დრო</small></span><ChevronRight/></button></div></Card><Card><SectionTitle title="ნიკას განრიგი" meta="VI კლასი"/><div className="compact-lessons">{lessons.map((l,i)=><div key={l[0]} className={i===1?'now':''}><time>{l[0]}</time><span><strong>{l[1]}</strong><small>{l[2]}</small></span>{i===1&&<b>ახლა</b>}</div>)}</div></Card></div></>}

function Inbox(){const [filter,setFilter]=useState('ყველა');return <><div className="inbox-tools"><div className="segmented">{['ყველა','საჭიროებს პასუხს','წაუკითხავი'].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'active':''}>{x}</button>)}</div><Action><Plus/> ახალი შეტყობინება</Action></div><Card className="inbox-card"><div className="message-list"><button className="selected"><span className="sender orange">ად</span><span><b>ადმინისტრაცია</b><strong>ექსკურსიის თანხმობა</strong><small>გთხოვთ, დაადასტუროთ 14 სექტემბრამდე.</small></span><time>10:24</time></button><button><span className="sender navy">მკ</span><span><b>მარიამ კ.</b><strong>ქართული ენა · უკუკავშირი</strong><small>ნიკამ პრეზენტაცია წარმატებით დაასრულა.</small></span><time>გუშინ</time></button><button><span className="sender green">ბი</span><span><b>ბიბლიოთეკა</b><strong>რესურსის დაბრუნება</strong><small>„პატარა პრინცი“ დასაბრუნებელია პარასკევს.</small></span><time>9 სექ</time></button></div><article className="message-detail"><span className="status-label">საჭიროებს პასუხს</span><h2>მეცნიერების მუზეუმში ვიზიტი</h2><p>VI კლასი 18 სექტემბერს მეცნიერების მუზეუმს ეწვევა. გამგზავრება სკოლიდან 10:00 საათზეა დაგეგმილი.</p><div className="message-facts"><span><small>პასუხის ვადა</small><strong>14 სექტემბერი</strong></span><span><small>ღირებულება</small><strong>25 ₾</strong></span></div><div className="inline-actions"><button className="suite-primary"><Check/> ვადასტურებ</button><button className="suite-secondary">უარის თქმა</button></div></article></Card></>}

function Portfolio(){return <><div className="student-strip"><span className="student-avatar">ნთ</span><div><h2>ნიკა თოდუა</h2><p>VI კლასი · 2026/27 სასწავლო წელი</p></div><Action><Plus/> ნამუშევრის დამატება</Action></div><div className="portfolio-grid"><Card className="featured-work"><span className="work-tag">რჩეული პროექტი</span><div className="work-art"><Sparkles/></div><h2>ჩემი მდგრადი ქალაქი</h2><p>საბუნებისმეტყველო პროექტი · გუნდური ნამუშევარი</p><footer><span><Star/> მასწავლებლის რჩეული</span><time>4 სექტემბერი</time></footer></Card><Card><SectionTitle title="წლის მონაპოვარი"/><div className="achievement"><strong>8</strong><span>ნამუშევარი</span></div><div className="achievement"><strong>3</strong><span>სერტიფიკატი</span></div><div className="achievement"><strong>12</strong><span>უკუკავშირი</span></div><button className="download-row"><FileCheck2/><span><strong>წლიური პორტფოლიო</strong><small>PDF · ჯერ არ შექმნილა</small></span><ChevronRight/></button></Card></div></>}

function Progress(){return <><div className="suite-stats"><Stat label="საერთო პროგრესი" value="82%" detail="+6% წინა პერიოდთან" tone="orange"/><Stat label="დასწრება" value="96%" detail="2 საპატიო გაცდენა"/><Stat label="დასრულებული დავალება" value="18/20" detail="2 მიმდინარე" tone="green"/></div><div className="suite-grid two"><Card><SectionTitle title="უნარების რუკა" meta="I პერიოდი"/><div className="skill-bars">{[['კითხვა და გააზრება',88],['ლოგიკური აზროვნება',76],['თანამშრომლობა',92],['დამოუკიდებელი მუშაობა',71]].map(x=><div key={x[0] as string}><span><strong>{x[0]}</strong><b>{x[1]}%</b></span><i><em style={{width:`${x[1]}%`}}/></i></div>)}</div></Card><Card><SectionTitle title="მასწავლებლის მოკლე შეფასება"/><blockquote>„ნიკა თავდაჯერებულად ერთვება გუნდურ მუშაობაში. შემდეგი ნაბიჯია, დამოუკიდებელი დავალებების დაგეგმვას მეტი დრო დაუთმოს.“</blockquote><span className="quote-by">მარიამ კ. · კლასის დამრიგებელი</span><button className="download-row"><FileCheck2/><span><strong>I პერიოდის ტაბელი</strong><small>დამტკიცების მოლოდინში</small></span><ChevronRight/></button></Card></div></>}

function Safety(){const [person,setPerson]=useState('თამარ მაისურაძე');return <div className="suite-grid two"><Card><SectionTitle title="დღევანდელი გაყვანა" meta="15:20"/><div className="pickup-code"><ShieldCheck/><small>ერთჯერადი კოდი</small><strong>482 719</strong><span>ძალაშია დღეს, 14:50–15:40</span></div><label className="suite-label">ბავშვს გაიყვანს<select value={person} onChange={e=>setPerson(e.target.value)}><option>თამარ მაისურაძე</option><option>გიორგი თოდუა</option></select></label><Action>ცვლილების შენახვა</Action></Card><Card><SectionTitle title="ნებართვები და თანხმობები"/><div className="consent-list"><div><span className="consent-icon"><Bus/></span><span><strong>მუზეუმში ვიზიტი</strong><small>საჭიროა პასუხი · 14 სექტემბრამდე</small></span><button>ნახვა</button></div><div><span className="consent-icon"><Check/></span><span><strong>ფოტოს გამოყენება</strong><small>დადასტურებულია · 2 სექტემბერი</small></span><button>ისტორია</button></div><div><span className="consent-icon"><Check/></span><span><strong>დამოუკიდებლად გასვლა</strong><small>არ არის ნებადართული</small></span><button>შეცვლა</button></div></div></Card></div>}

function Health(){return <><div className="privacy-banner"><ShieldCheck/><div><strong>დაცული სამედიცინო ჩანაწერი</strong><span>ხედავენ მხოლოდ მშობელი და უფლებამოსილი თანამშრომლები. ყველა ნახვა აღირიცხება.</span></div><button>წვდომის ისტორია</button></div><div className="suite-grid two"><Card><SectionTitle title="მნიშვნელოვანი ინფორმაცია"/><div className="health-alert"><HeartPulse/><span><strong>თხილზე ალერგია</strong><small>მაღალი მნიშვნელობა · სამოქმედო გეგმა დართულია</small></span></div><div className="health-row"><span>გადაუდებელი კონტაქტი</span><strong>ია თოდუა · +995 5•• •• •• 20</strong></div><div className="health-row"><span>ოჯახის ექიმი</span><strong>ინფორმაცია დამატებული არ არის</strong></div></Card><Card><SectionTitle title="ინციდენტების ჟურნალი" meta="ამ სასწავლო წელს"/><div className="incident"><time>8 სექტემბერი · 12:35</time><strong>მსუბუქი ნაკაწრი სპორტის გაკვეთილზე</strong><p>დამუშავებულია ადგილზე. მშობელი ინფორმირებულია 12:42-ზე.</p></div><button className="suite-secondary full">სამედიცინო ჩანაწერის განახლება</button></Card></div></>}

function Teacher(){return <><div className="teacher-hero"><div><span>მასწავლებლის დღე</span><h2>შემდეგი გაკვეთილი 24 წუთში</h2><p>VI კლასი · ქართული ენა · ოთახი 204</p></div><button><ClipboardCheck/> დასწრების გახსნა</button></div><div className="suite-grid three"><Card><SectionTitle title="დღის გაკვეთილები"/><div className="teacher-count"><strong>5</strong><span>2 დასრულებული · 3 დარჩა</span></div></Card><Card><SectionTitle title="შესაფასებელი"/><div className="teacher-count"><strong>12</strong><span>ნამუშევარი · ვადა ხვალ</span></div></Card><Card><SectionTitle title="მშობლის წერილები"/><div className="teacher-count"><strong>3</strong><span>1 საჭიროებს პასუხს</span></div></Card></div><Card><SectionTitle title="ჩემი კლასები" meta="2026/27"/><div className="class-grid">{[['VI ა','ქართული ენა','24 მოსწავლე'],['VII ბ','ქართული ენა','22 მოსწავლე'],['IX ა','ლიტერატურა','21 მოსწავლე']].map(x=><button key={x[0]}><span className="class-letter">{x[0]}</span><span><strong>{x[1]}</strong><small>{x[2]}</small></span><ChevronRight/></button>)}</div></Card></>}

function Substitute(){return <><Card><SectionTitle title="ჩანაცვლების ახალი მოთხოვნა" meta="ხუთშაბათი"/><div className="absence-row"><span className="sender navy">მკ</span><span><strong>მარიამ კაპანაძე</strong><small>ქართული ენა · 3 გაკვეთილი · 12 სექტემბერი</small></span><span className="status-label">საჭიროა შემცვლელი</span></div></Card><div className="suite-grid two"><Card><SectionTitle title="შესაძლო შემცვლელები"/><div className="candidate selected"><span><strong>ანა ჯაფარიძე</strong><small>თავისუფალია სამივე გაკვეთილზე</small></span><b>საუკეთესო შესაბამისობა</b></div><div className="candidate"><span><strong>ნინო აბაშიძე</strong><small>კონფლიქტი 12:00 საათზე</small></span><b>2/3 გაკვეთილი</b></div><Action>ანას დანიშვნა</Action></Card><Card><SectionTitle title="გადასაცემი მასალა"/><div className="file-row"><FileCheck2/><span><strong>VI კლასი · გაკვეთილის გეგმა</strong><small>PDF · 2.4 MB</small></span><Check/></div><div className="file-row"><FileCheck2/><span><strong>საშინაო დავალება</strong><small>დოკუმენტი · განახლდა დღეს</small></span><Check/></div></Card></div></>}

function Admissions(){return <><div className="admission-top"><div className="suite-stats"><Stat label="ახალი განაცხადი" value="18" detail="ამ კვირაში +4" tone="orange"/><Stat label="დაგეგმილი ვიზიტი" value="9" detail="შემდეგი — დღეს 15:00"/><Stat label="თავისუფალი ადგილი" value="32" detail="ყველა კლასში" tone="green"/></div><Action><Plus/> ოჯახის დამატება</Action></div><Card><SectionTitle title="მიღების გზა" meta="2026/27"/><div className="pipeline">{[['დაინტერესდა',28,'orange'],['ვიზიტი',14,'blue'],['განაცხადი',11,'navy'],['ინტერვიუ',7,'green'],['ჩარიცხვა',4,'dark']].map(x=><div key={x[0] as string}><span><i className={x[2] as string}/><strong>{x[0]}</strong></span><b>{x[1]}</b><small>ოჯახი</small></div>)}</div></Card><Card><SectionTitle title="დღევანდელი ოჯახები"/><div className="crm-table"><div><span className="sender orange">ნკ</span><span><strong>ნატა კიკნაძე</strong><small>დაწყებითი საფეხური</small></span><b>ვიზიტი · 15:00</b><button>გახსნა</button></div><div><span className="sender green">დგ</span><span><strong>დავით გიორგაძე</strong><small>საბაზო საფეხური</small></span><b>დოკუმენტები</b><button>გახსნა</button></div></div></Card></>}

function Operations(){return <div className="service-cards"><Card><span className="service-icon orange"><Bus/></span><h2>ტრანსპორტი</h2><p>მარშრუტი 03 · საღამოს გასვლა 16:10</p><div className="route-line"><i/><span><strong>სკოლა</strong><small>16:10</small></span><i/><span><strong>დიღომი</strong><small>16:32</small></span><i/><span><strong>საბურთალო</strong><small>16:51</small></span></div><button className="suite-secondary full">მარშრუტის დეტალები</button></Card><Card><span className="service-icon green"><Sparkles/></span><h2>კვება</h2><p>დღევანდელი მენიუ · ალერგენები გათვალისწინებულია</p><ul><li>ბოსტნეულის სუპი</li><li>ქათამი ბრინჯით</li><li>სეზონური ხილი</li></ul><button className="suite-secondary full">კვირის მენიუ</button></Card><Card><span className="service-icon navy"><Star/></span><h2>კლუბები</h2><p>რობოტიკის კლუბი · სამშაბათი და ხუთშაბათი</p><div className="capacity"><span><i style={{width:'78%'}}/></span><small>18/23 ადგილი შევსებულია</small></div><button className="suite-primary full">რეგისტრაცია <ArrowRight/></button></Card></div>}

function Director(){return <><div className="suite-stats four"><Stat label="დღეს სკოლაში" value="94.8%" detail="438 / 462 მოსწავლე" tone="green"/><Stat label="დაგვიანება" value="17" detail="−4 გასულ ხუთშაბათთან" tone="orange"/><Stat label="დასამტკიცებელი" value="8" detail="დოკუმენტი და ტაბელი"/><Stat label="გადახდილი" value="87%" detail="მიმდინარე თვე" tone="navy"/></div><div className="suite-grid director-grid"><Card><SectionTitle title="დასწრების დინამიკა" meta="ბოლო 7 დღე"/><div className="big-chart">{[82,91,87,96,94,89,95].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{['პარ','სამ','ოთხ','ხუთ','პარ','სამ','დღეს'][i]}</span></div>)}</div></Card><Card><SectionTitle title="ყურადღების ცენტრი"/><div className="pulse-list"><button><span className="pulse-num">8</span><span><strong>დასამტკიცებელი დოკუმენტი</strong><small>ყველაზე ძველი · 2 დღე</small></span><ChevronRight/></button><button><span className="pulse-num orange">6</span><span><strong>განმეორებითი დაგვიანება</strong><small>ბოლო 30 დღის ჭრილში</small></span><ChevronRight/></button><button><span className="pulse-num green">3</span><span><strong>მიღების ინტერვიუ</strong><small>დაგეგმილია დღეს</small></span><ChevronRight/></button></div></Card></div></>}

function Platform(){const [theme,setTheme]=useState('აისი');return <><div className="suite-grid platform-grid"><Card><SectionTitle title="სკოლები" meta="2 აქტიური"/><button className="tenant-row selected"><span className="school-symbol"><School/></span><span><strong>სკოლა აისი</strong><small>aisi.edu.ge · 462 მოსწავლე</small></span><b>აქტიური</b></button><button className="tenant-row"><span className="school-symbol muted"><School/></span><span><strong>ახალი სკოლა</strong><small>school.demo.ge · მომზადება</small></span><b>საცდელი</b></button><button className="suite-secondary full"><Plus/> სკოლის დამატება</button></Card><Card><SectionTitle title="ბრენდის სწრაფი მართვა"/><div className="brand-choice"><button className={theme==='აისი'?'active':''} onClick={()=>setTheme('აისი')}><i className="aisi-color"/>აისი</button><button className={theme==='ლურჯი'?'active':''} onClick={()=>setTheme('ლურჯი')}><i className="blue-color"/>ლურჯი</button></div><div className="mini-brand"><Logo/><small>{theme==='აისი'?'მზისფერი თემა':'ლურჯი თემა'} · ცოცხალი ნახვა</small></div></Card></div><Card><SectionTitle title="ჩართული მოდულები" meta="აისის პაკეტი"/><div className="module-switches">{['სწავლა და დასწრება','კომუნიკაცია','დოკუმენტები','გადახდები','მიღების CRM','ტრანსპორტი და კვება'].map((x,i)=><label key={x}><span><strong>{x}</strong><small>{i<4?'Core პაკეტი':'დამატებითი მოდული'}</small></span><input type="checkbox" defaultChecked={i<5}/><i/></label>)}</div></Card></>}
