'use client';
import {useEffect,useState} from 'react';
import {Search,ArrowUpRight,ArrowLeft,BookOpen} from 'lucide-react';
import {Logo} from '../AisiConcept';
import content from './content.json';
import './school.css';
const categories=[{id:'pages',label:'სკოლის შესახებ'},{id:'posts',label:'სკოლის ამბები'},{id:'teachers',label:'პედაგოგები'},{id:'documents',label:'დოკუმენტები'}];
export default function SchoolContent(){
 const [category,setCategory]=useState('pages'),[query,setQuery]=useState(''),[active,setActive]=useState<string|null>('wp-pages-2371');
 useEffect(()=>{const key=new URLSearchParams(window.location.search).get('item');const item=content.find(x=>x.key===key);if(item){setCategory(item.type);setActive(item.key)}},[]);
 const rows=content.filter(r=>r.type===category&&(r.title+' '+r.body).includes(query.trim()));
 const item=content.find(r=>r.key===active);
 return <main className="school-archive"><header><a href="/" aria-label="აისი — მთავარი"><Logo/></a><a href="/">ვებგვერდზე დაბრუნება <ArrowUpRight size={16}/></a></header><section className="archive-hero"><div className="eyebrow">აისის ისტორია, ადამიანები და ყოველდღიურობა</div><h1>გაიცანი <em>აისი.</em></h1><p>არსებული საიტის ინფორმაცია — ერთ სივრცეში, ახალი ფორმით.</p><small>სარედაქციო ვერსია · მიმდინარე წესები და მონაცემები სკოლის დასადასტურებელია</small></section><nav className="archive-categories" aria-label="კონტენტის კატეგორია">{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setQuery('');setActive(null)}}>{c.label}<span>{content.filter(r=>r.type===c.id).length}</span></button>)}</nav><div className="archive-layout"><aside><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="კონტენტის ძიება" placeholder="მოძებნე ინფორმაცია"/></label><div className="archive-list">{rows.map(r=><button key={r.key} aria-pressed={active===r.key} onClick={()=>setActive(r.key)}><strong>{r.title}</strong>{r.type==='posts'&&r.published_at&&<small>{new Date(r.published_at).toLocaleDateString('ka-GE',{year:'numeric',month:'long',day:'numeric'})}</small>}</button>)}{!rows.length&&<p>მონაცემი ვერ მოიძებნა.</p>}</div></aside><article className="archive-article">{item?<><div className="article-kicker"><BookOpen size={17}/>{categories.find(c=>c.id===item.type)?.label}</div><h2>{item.title}</h2>{item.image&&<img className="article-cover" src={item.image} alt={item.title}/>}<div className="article-body">{item.body.split(/\n\n+/).map((p,i)=><p key={i}>{p}</p>)}</div>{item.links.filter(l=>l.url.startsWith('http')&&!l.url.includes('#')).length>0&&<details className="source-resources"><summary>წყაროში მითითებული ბმულები და მასალები</summary>{item.links.filter(l=>l.url.startsWith('http')&&!l.url.includes('#')).map((l,i)=><a key={i} href={l.url} target="_blank" rel="noreferrer">{l.label.trim()||'მასალის გახსნა'} <ArrowUpRight size={14}/></a>)}</details>}<div className="article-source"><a href={item.source_url} target="_blank" rel="noreferrer">ორიგინალის ნახვა <ArrowUpRight size={15}/></a><p>{item.editorial_status==='rewritten_needs_approval'?'ტექსტი სარედაქციოდ დამუშავებულია; გამოქვეყნებამდე სკოლამ უნდა დაამტკიცოს.':'წყაროს ტექსტი გასუფთავებულია ძველი გაფორმებისგან. ინფორმაცია შეიძლება ისტორიული იყოს.'}</p></div></>:<div className="archive-empty"><BookOpen size={42}/><h2>აირჩიე ამბავი ან გვერდი.</h2><p>მარცხენა სიაში თავმოყრილია არსებული საიტიდან გადმოტანილი ინფორმაცია.</p></div>}</article></div><footer><a href="/"><ArrowLeft size={16}/>მთავარ გვერდზე</a><p>ორიგინალები და იმპორტის სრული პაკეტი შენახულია პროექტის content-migration/ საქაღალდეში.</p></footer></main>
}
